# Generated by Django 5.2.3 on 2025-06-30 01:15

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre del Ítem')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Cantidad')),
                ('unit', models.CharField(max_length=50, verbose_name='Unidad')),
                ('location', models.CharField(max_length=255, verbose_name='Ubicación')),
                ('last_updated', models.DateField(auto_now=True, verbose_name='Última Actualización')),
                ('status', models.CharField(max_length=50, verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'Ítem de Inventario',
                'verbose_name_plural': 'Ítems de Inventario',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('ADMIN', 'Administrador'), ('SUPERVISOR', 'Supervisor'), ('EMPLOYEE', 'Empleado')], default='EMPLOYEE', max_length=20, verbose_name='Rol de Usuario')),
                ('id_number', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Número de Identificación')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono')),
                ('fingerprint_id', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='ID de Huella Dactilar')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuario Personalizado',
                'verbose_name_plural': 'Usuarios Personalizados',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='AccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_type', models.CharField(choices=[('ENTRADA', 'Entrada'), ('SALIDA', 'Salida')], max_length=10, verbose_name='Tipo de Acceso')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora')),
                ('area', models.CharField(max_length=100, verbose_name='Área')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notas')),
                ('health_status_or_rfc', models.CharField(blank=True, max_length=255, null=True, verbose_name='Estado de Salud/RFC')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_logs', to=settings.AUTH_USER_MODEL, verbose_name='Empleado')),
            ],
            options={
                'verbose_name': 'Registro de Acceso',
                'verbose_name_plural': 'Registros de Acceso',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='GasRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Fecha')),
                ('time', models.TimeField(verbose_name='Hora')),
                ('location', models.CharField(max_length=255, verbose_name='Ubicación')),
                ('gas_type', models.CharField(choices=[('METANO', 'Metano (CH₄)'), ('CO', 'Monóxido de Carbono (CO)'), ('CO2', 'Dióxido de Carbono (CO₂)'), ('H2S', 'Ácido Sulfhídrico (H₂S)')], max_length=50, verbose_name='Tipo de Gas')),
                ('level', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Nivel')),
                ('unit', models.CharField(choices=[('%', '%'), ('PPM', 'ppm')], max_length=10, verbose_name='Unidad')),
                ('status', models.CharField(max_length=50, verbose_name='Estado')),
                ('observations', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gas_records', to=settings.AUTH_USER_MODEL, verbose_name='Registrado por')),
            ],
            options={
                'verbose_name': 'Registro de Gas',
                'verbose_name_plural': 'Registros de Gases',
                'ordering': ['-date', '-time'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre del Proyecto')),
                ('location', models.CharField(max_length=255, verbose_name='Ubicación')),
                ('start_date', models.DateField(verbose_name='Fecha de Inicio')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('status', models.CharField(default='Activo', max_length=50, verbose_name='Estado del Proyecto')),
                ('manager', models.ForeignKey(blank=True, limit_choices_to={'role': 'SUPERVISOR'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_projects', to=settings.AUTH_USER_MODEL, verbose_name='Supervisor Asignado')),
            ],
            options={
                'verbose_name': 'Proyecto',
                'verbose_name_plural': 'Proyectos',
            },
        ),
        migrations.CreateModel(
            name='ProductionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Fecha de Producción')),
                ('material_type', models.CharField(max_length=100, verbose_name='Tipo de Material')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Cantidad')),
                ('unit', models.CharField(max_length=50, verbose_name='Unidad')),
                ('quality', models.CharField(blank=True, max_length=50, null=True, verbose_name='Calidad')),
                ('observations', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='production_entries', to=settings.AUTH_USER_MODEL, verbose_name='Empleado')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='production_records', to='api.project', verbose_name='Proyecto')),
            ],
            options={
                'verbose_name': 'Registro de Producción',
                'verbose_name_plural': 'Registros de Producción',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre de la Herramienta')),
                ('category', models.CharField(max_length=100, verbose_name='Categoría')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('quantity', models.IntegerField(verbose_name='Cantidad')),
                ('status', models.CharField(max_length=50, verbose_name='Estado')),
                ('last_revision_date', models.DateField(blank=True, null=True, verbose_name='Fecha Última Revisión')),
                ('location', models.CharField(max_length=255, verbose_name='Ubicación')),
                ('observations', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tools', to=settings.AUTH_USER_MODEL, verbose_name='Asignado a')),
            ],
            options={
                'verbose_name': 'Herramienta',
                'verbose_name_plural': 'Herramientas',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='WorkFront',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre del Frente')),
                ('location', models.CharField(max_length=255, verbose_name='Ubicación')),
                ('status', models.CharField(choices=[('ACTIVO', 'Activo'), ('PAUSADO', 'Pausado'), ('FINALIZADO', 'Finalizado'), ('PLANIFICADO', 'Planificado')], default='PLANIFICADO', max_length=50, verbose_name='Estado')),
                ('start_date', models.DateField(verbose_name='Fecha de Inicio')),
                ('estimated_end_date', models.DateField(verbose_name='Fecha Estimada de Finalización')),
                ('workers', models.IntegerField(verbose_name='Número de Trabajadores')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción del Trabajo')),
                ('progress', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Progreso (%)')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_fronts', to='api.project', verbose_name='Proyecto Asociado')),
                ('supervisor', models.ForeignKey(blank=True, limit_choices_to={'role': 'SUPERVISOR'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervised_work_fronts', to=settings.AUTH_USER_MODEL, verbose_name='Supervisor del Frente')),
            ],
            options={
                'verbose_name': 'Frente de Trabajo',
                'verbose_name_plural': 'Frentes de Trabajo',
                'ordering': ['-start_date'],
            },
        ),
    ]
