# Generated by Django 5.2.1 on 2025-07-08 02:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accesslog',
            old_name='cedula',
            new_name='id_number',
        ),
    ]
