# Generated by Django 5.2.1 on 2025-07-09 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_cedula_accesslog_id_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gasrecord',
            name='gas_type',
            field=models.CharField(choices=[('METANO', 'Metano (CH₄)'), ('CO', 'Monóxido de Carbono (CO)'), ('CO2', 'Dióxido de Carbono (CO₂)'), ('H2S', 'Ácido Sulfhídrico (H₂S)'), ('OXYGEN', 'Oxígeno (O₂)')], max_length=50, verbose_name='Tipo de Gas'),
        ),
    ]
