# Generated by Django 5.2.1 on 2025-07-09 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_gasrecord_gas_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='report',
            options={},
        ),
        migrations.RenameField(
            model_name='report',
            old_name='date_created',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='report',
            old_name='content',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='fingerprint_id',
        ),
        migrations.AlterField(
            model_name='report',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
