# Generated by Django 5.2.1 on 2025-07-17 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_report_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gasrecord',
            name='is_active',
            field=models.CharField(blank=True, null=True),
        ),
    ]
