# Generated by Django 5.2.1 on 2025-07-17 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_gasrecord_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gasrecord',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
