# Generated by Django 5.2.1 on 2025-07-17 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_gasrecord_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='workfront',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
