# Generated by Django 5.2.1 on 2025-07-17 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_workfront_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workfront',
            name='status',
        ),
    ]
